name: Test Push
on:
  push:
    branches:
      - '*'

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v1
        with:
          go-version: 1.13.x
      - uses: actions/checkout@v1
        with:
          fetch-depth: 1
      - name: install golangci-lint
        run: curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin v1.21.0
      - name: install golint
        run: go get -u golang.org/x/lint/golint
      - name: golint
        run: $(go env GOPATH)/bin/golint -set_exit_status ./...
      - name: golangci-lint
        run: $(go env GOPATH)/bin/golangci-lint run

  test:
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - uses: actions/setup-go@v1
        with:
          go-version: 1.13.x
      - uses: actions/checkout@v1
        with:
          fetch-depth: 1
      - name: docker postgres
        run: docker pull postgres:11.5
      - name: run tests
        run: ./test.sh
